### ISSUE TITLE
Unable to retrieve list of all work item types

### ISSUE THREAD

**Issue by pamurp7789** [jelledruyts/TfsTeamProjectManager#21]
After querying for the latest set of work items types in my VSTS project, I noticed that some of them weren't being returned.

Found the error in task logs:

Processing Team Project "[MyProject]"
An error occurred while processing Team Project "[MyProject]": VS402337: The number of work items returned exceeds the size limit of 20000. Change the query to return fewer items.
Microsoft.TeamFoundation.WorkItemTracking.Client.VerbatimMessageException: VS402337: The number of work items returned exceeds the size limit of 20000. Change the query to return fewer items. ---> System.Web.Services.Protocols.SoapException: VS402337: The number of work items returned exceeds the size limit of 20000. Change the query to return fewer items.
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.RetryHandler.HandleSoapException(SoapException se)
   at Microsoft.TeamFoundation.WorkItemTracking.Proxy.WorkItemServer.QueryWorkitemCount(String requestId, XmlElement psQuery, Boolean useMaster, Int32& count, DateTime& asOfDate, MetadataTableHaveEntry[] metadataHave, String& dbStamp, IMetadataRowSets& metadata)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.QueryWorkItemCount(String requestid, XmlElement queryXml, DateTime& asof)
   --- End of inner exception stack trace ---
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.QueryWorkItemCount(String requestid, XmlElement queryXml, DateTime& asof)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.Query.RunCountQuery(String requestId)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.QueryCount(String wiql, IDictionary context)
   at TeamProjectManager.Modules.WorkItemConfiguration.WorkItemTypes.WorkItemTypesViewModel.<>c__DisplayClass82_0.<GetWorkItemTypes>b__0(Object sender, DoWorkEventArgs e) in C:\Users\jelled\Desktop\Code\TfsTeamProjectManager\Repo\TeamProjectManager.Modules.WorkItemConfiguration\WorkItemTypes\WorkItemTypesViewModel.cs:line 169
Retrieved 22 work item types

I also hit this in my own integration with VSTS, and here is the code I used to work around it.  You could plug in something similar to this.

```
// There is a VSO limit of a query returning 20,000 results. Split into groups of 10,000 items maximum.
var results = new List<WorkItemReference>();
var counter = 10000;
var moreResults = true;
while (moreResults)
{
	List<WorkItemReference> currentResults = this.WitClient.QueryByWiqlAsync(new Wiql
	{
		Query = $"SELECT System.ID FROM WorkItems WHERE System.TeamProject = '{Project}' AND {customQuery} AND System.ID >= {counter - 10000} AND System.ID < {counter}"}).Result.WorkItems.ToList();

	if (currentResults.Count == 0)
	{
		// Verify there are no more items
		try
		{
			results.AddRange(this.WitClient.QueryByWiqlAsync(new Wiql
			{
				Query = $"SELECT System.ID FROM WorkItems WHERE System.TeamProject = '{Project}' AND {customQuery} AND System.ID >= {counter}"
			}).Result.WorkItems.ToList());
 
			moreResults = false;
		}
		catch (Exception e)
		{
			if (e.ToString().Contains("VS402337"))
			{
				// There are still more results, so increment and try again.
			}
			else
			{
				throw;
			}
		}
	}
	else
	{
		results.AddRange(currentResults);
	}

	counter += 10000;
}
```

**Comment by jelledruyts** [comment]
Thanks for reporting this, interestingly I'm not asking to return the actual results but only a **count** so it's weird that it's throwing an exception in this case.

I'll see if I can make it work easily, but if it can't get the count then the code should just ignore the exception since it's just showing the number of work items for that work item type as a piece of extra information in the list anyway (i.e. nothing critical).

**Comment by pamurp7789** [comment]
Thanks, I would ignore it but it is preventing the ability for me to see the custom work item types being retrieved in the results.

I dug a little deeper and it looks like in VSO I have more than 20,000 items of a single work item type.  Even in the VSO website this causes query errors if I try to retrieve all of the items of this specific type.  Maybe its this line that is causing the issue?

                            var workItemCount = store.QueryCount("SELECT [System.Id] FROM WorkItems WHERE [System.WorkItemType] = @WorkItemType AND [System.TeamProject] = @TeamProject", parameters);

If there are more than 20,000 results, I believe this throws.

**Comment by jelledruyts** [comment]
Should be fixed in the latest release now, see https://github.com/jelledruyts/TfsTeamProjectManager/releases/tag/v2.2.6365
