### ISSUE TITLE
Azure DevOps Server 2019 compatibility

### ISSUE THREAD

**Issue by evertonmc** [jelledruyts/TfsTeamProjectManager#45]
```
Processing Team Project "demos"
An error occurred while processing Team Project "demos": The feature is disabled. Contact your Azure DevOps Server administrator. Process Id: 03e4e666-dae6-4b58-a2ff-ab65fc17a4f6, Project Id: de5520dd-37a7-46d6-8537-d2ba20af34db
Microsoft.VisualStudio.Services.Common.VssServiceException: The feature is disabled. Contact your Azure DevOps Server administrator. Process Id: 03e4e666-dae6-4b58-a2ff-ab65fc17a4f6, Project Id: de5520dd-37a7-46d6-8537-d2ba20af34db
   at Microsoft.TeamFoundation.WorkItemTracking.Client.Provision.ProvisionClass.ExportWorkItemTypeUsingServerProvisioning(Int32 projectId, Nullable`1 typeId, Boolean includeGlobalList, XmlDocument& template)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.Provision.ProvisionClass.ExportWorkItemType(Int32 projectId, Int32 typeId, Boolean withGlobalListsFlag)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.Provision.ProvisionClass.ExportWorkItemType(WorkItemStore ws, Int32 projectId, Int32 typeId, Boolean withGlobalListsFlag)
   at TeamProjectManager.Modules.WorkItemConfiguration.WorkItemTypes.WorkItemTypesViewModel.<>c__DisplayClass82_0.<GetWorkItemTypes>b__0(Object sender, DoWorkEventArgs e) in C:\Users\jelled\Desktop\Code\TfsTeamProjectManager\Repo\TeamProjectManager.Modules.WorkItemConfiguration\WorkItemTypes\WorkItemTypesViewModel.cs:line 187
Retrieved 0 work item types
```

**Comment by evertonmc** [comment]
Get Work Item Types not working

**Comment by gopireddyravindar** [comment]
were you able to  fix the issue?

**Comment by erelado** [comment]
Currently running on-prem ADO 2019 and have no issues getting the work item types.
